routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('providers', 'ProviderController');
Route::resource('transports', 'TransportController');
Route::resource('warehouses', 'WarehouseController');
Route::resource('products', 'ProductController');

resources/views/warehouses/create.blade.php
@extends('layouts.app')

@section('title', 'New Warehouse')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <form action="{{ route('warehouses.store') }}" method="post">
        @csrf
        <div class="form-group"><label for="name">Company</label><input type="text" name="name" id="name" class="form-control"></div>
        <div class="form-row">
            <div class="form-group col-md"><label for="first_name">First Name</label><input type="text" name="first_name" id="first_name" class="form-control"></div>
            <div class="form-group col-md"><label for="last_name">Last Name</label><input type="text" name="last_name" id="last_name" class="form-control"></div>
            <div class="form-group col-md"><label for="job_title">Job Title</label><input type="text" name="job_title" id="job_title" class="form-control"></div>
        </div>
        <div class="form-row">
            <div class="form-group col-md"><label for="email">Email</label><input type="email" name="email" id="email" class="form-control"></div>
            <div class="form-group col-md"><label for="phone">Phone</label><input type="text" name="phone" id="phone" class="form-control"></div>
        </div>
        <div class="form-group"><button type="submit" class="btn btn-primary mr-3">Save</button><a href="{{ route('warehouses.index') }}" class="btn btn-danger">Cancel</a></div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/warehouses/edit.blade.php
@extends('layouts.app')

@section('title', 'Update Warehouse')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <form action="{{ route('warehouses.update', $warehouse->id) }}" method="post">
        @csrf
        @method('PATCH')
        <div class="form-group"><label for="name">Company</label><input type="text" name="name" id="name" class="form-control" value="{{ $warehouse->name }}"></div>
        <div class="form-row">
            <div class="form-group col-md"><label for="first_name">First Name</label><input type="text" name="first_name" id="first_name" class="form-control" value="{{ $warehouse->first_name }}"></div>
            <div class="form-group col-md"><label for="last_name">Last Name</label><input type="text" name="last_name" id="last_name" class="form-control" value="{{ $warehouse->last_name }}"></div>
            <div class="form-group col-md"><label for="job_title">Job Title</label><input type="text" name="job_title" id="job_title" class="form-control" value="{{ $warehouse->job_title }}"></div>
        </div>
        <div class="form-row">
            <div class="form-group col-md"><label for="email">Email</label><input type="email" name="email" id="email" class="form-control" value="{{ $warehouse->email }}"></div>
            <div class="form-group col-md"><label for="phone">Phone</label><input type="text" name="phone" id="phone" class="form-control" value="{{ $warehouse->phone }}"></div>
        </div>
        <div class="form-group"><button type="submit" class="btn btn-primary mr-3">Update</button><a href="{{ route('warehouses.index') }}" class="btn btn-danger">Cancel</a></div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/warehouses/index.blade.php
@extends('layouts.app')

@section('title', 'Warehouses')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <a href="{{ route('warehouses.create') }}" class="btn btn-primary mb-2">New Warehouse</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Company</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach ($warehouses as $warehouse)
                <tr>
                    <td><a href="{{ route('warehouses.show', $warehouse->id) }}">{{ $warehouse->name }}</a></td>
                    <td class="text-right">
                        <form action="{{ route('warehouses.destroy', $warehouse->id) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">X</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection

resources/views/warehouses/show.blade.php
@extends('layouts.app')

@section('title', $warehouse->name)

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <table class="table">
            <tr>
                <th>Contact Name:</th>
                <td>{{ $warehouse->first_name }} {{ $warehouse->last_name }}</td>
            </tr>
            <tr>
                <th>Job Title:</th>
                <td>{{ $warehouse->job_title }}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{ $warehouse->email }}</td>
            </tr>
            <tr>
                <th>Phone:</th>
                <td>{{ $warehouse->phone }}</td>
            </tr>
        </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <a href="{{ route('warehouses.edit', $warehouse->id) }}" class="btn btn-outline-secondary">Update</a>
            <form action="{{ route('warehouses.destroy', $warehouse->id) }}" method="post" style="display: inline;">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-outline-danger" type="submit">Delete</button>
                        </form>
        </div>
    </div>
</div>
@endsection