routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('providers', 'ProviderController');
Route::resource('transports', 'TransportController');
Route::resource('warehouses', 'WarehouseController');
Route::resource('products', 'ProductController');

app/Provider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Provider extends Model
{
    protected $fillable = [
        'company', 'first_name', 'last_name', 'email', 'phone', 'job_title'
    ];
}

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Provider;

class ProviderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $providers = Provider::all();
        return view('providers.index', ['providers' => $providers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('providers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $provider = new Provider([
            'company' => $request->get('name'),
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'phone' => $request->get('phone'),
            'job_title' => $request->get('job_title')
        ]);
        $provider->save();
        return redirect()->route('providers.index')->with('success', 'Provider saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $provider = Provider::find($id);
        return view('providers.show', ['provider' => $provider]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $provider = Provider::find($id);
        return view('providers.edit', ['provider' => $provider]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'name' => 'required'
        ]);

        $provider = Provider::find($id);
        $provider->company = $request->get('name');
        $provider->first_name = $request->get('first_name');
        $provider->last_name = $request->get('last_name');
        $provider->email = $request->get('email');
        $provider->phone = $request->get('phone');
        $provider->job_title = $request->get('job_title');

        $provider->save();

        return redirect()->route('providers.show', $provider->id)->with('success', 'Provider updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $provider = Provider::find($id);
        $provider->delete();

        return redirect()->route('providers.index')->with('success', 'Provider deleted successfully!');
    }
}

resources/views/providers/create.blade.php
@extends('layouts.app')

@section('title', 'New Provider')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <form action="{{ route('providers.store') }}" method="post">
        @csrf
        <div class="form-group"><label for="name">Company</label><input type="text" name="name" id="name" class="form-control"></div>
        <div class="form-row">
            <div class="form-group col-md"><label for="first_name">First Name</label><input type="text" name="first_name" id="first_name" class="form-control"></div>
            <div class="form-group col-md"><label for="last_name">Last Name</label><input type="text" name="last_name" id="last_name" class="form-control"></div>
            <div class="form-group col-md"><label for="job_title">Job Title</label><input type="text" name="job_title" id="job_title" class="form-control"></div>
        </div>
        <div class="form-row">
            <div class="form-group col-md"><label for="email">Email</label><input type="email" name="email" id="email" class="form-control"></div>
            <div class="form-group col-md"><label for="phone">Phone</label><input type="text" name="phone" id="phone" class="form-control"></div>
        </div>
        <div class="form-group"><button type="submit" class="btn btn-primary mr-3">Save</button><a href="{{ route('providers.index') }}" class="btn btn-danger">Cancel</a></div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/providers/edit.blade.php
@extends('layouts.app')

@section('title', 'Update Provider')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <form action="{{ route('providers.update', $provider->id) }}" method="post">
        @csrf
        @method('PATCH')
        <div class="form-group"><label for="name">Company</label><input type="text" name="name" id="name" class="form-control" value="{{ $provider->company }}"></div>
        <div class="form-row">
            <div class="form-group col-md"><label for="first_name">First Name</label><input type="text" name="first_name" id="first_name" class="form-control" value="{{ $provider->first_name }}"></div>
            <div class="form-group col-md"><label for="last_name">Last Name</label><input type="text" name="last_name" id="last_name" class="form-control" value="{{ $provider->last_name }}"></div>
            <div class="form-group col-md"><label for="job_title">Job Title</label><input type="text" name="job_title" id="job_title" class="form-control" value="{{ $provider->job_title }}"></div>
        </div>
        <div class="form-row">
            <div class="form-group col-md"><label for="email">Email</label><input type="email" name="email" id="email" class="form-control" value="{{ $provider->email }}"></div>
            <div class="form-group col-md"><label for="phone">Phone</label><input type="text" name="phone" id="phone" class="form-control" value="{{ $provider->phone }}"></div>
        </div>
        <div class="form-group"><button type="submit" class="btn btn-primary mr-3">Update</button><a href="{{ route('providers.index') }}" class="btn btn-danger">Cancel</a></div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/providers/index.blade.php
@extends('layouts.app')

@section('title', 'Providers')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <a href="{{ route('providers.create') }}" class="btn btn-primary mb-2">New Provider</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Company</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach ($providers as $provider)
                <tr>
                    <td><a href="{{ route('providers.show', $provider->id) }}">{{ $provider->company }}</a></td>
                    <td class="text-right">
                        <form action="{{ route('providers.destroy', $provider->id) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">X</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection

resources/views/providers/show.blade.php
@extends('layouts.app')

@section('title', $provider->company)

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <table class="table">
            <tr>
                <th>Contact Name:</th>
                <td>{{ $provider->first_name }} {{ $provider->last_name }}</td>
            </tr>
            <tr>
                <th>Job Title:</th>
                <td>{{ $provider->job_title }}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{ $provider->email }}</td>
            </tr>
            <tr>
                <th>Phone:</th>
                <td>{{ $provider->phone }}</td>
            </tr>
        </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <a href="{{ route('providers.edit', $provider->id) }}" class="btn btn-outline-secondary">Update</a>
            <form action="{{ route('providers.destroy', $provider->id) }}" method="post" style="display: inline;">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-outline-danger" type="submit">Delete</button>
                        </form>
        </div>
    </div>
</div>
@endsection