routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('providers', 'ProviderController');
Route::resource('transports', 'TransportController');
Route::resource('warehouses', 'WarehouseController');
Route::resource('products', 'ProductController');

app/Transport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transport extends Model
{
    protected $fillable = [
        'name', 'first_name', 'last_name', 'email', 'phone', 'job_title'
    ];
}

app/Http/Controllers/TransportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Transport;

class TransportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transports = Transport::all();
        return view('transports.index', compact('transports'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transports.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required'
        ]);

        $transport = new Transport([
            'name' => $request->get('name'),
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'phone' => $request->get('phone'),
            'job_title' => $request->get('job_title')
        ]);
        $transport->save();

        return redirect()->route('transports.index')->with('success', 'Transport saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transport = Transport::find($id);
        return view('transports.show', compact('transport'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $transport = Transport::find($id);
        return view('transports.edit', compact('transport'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'name' => 'required',
            'phone' => 'required'
        ]);

        $transport = Transport::find($id);
        $transport->name = $request->get('name');
        $transport->first_name = $request->get('first_name');
        $transport->last_name = $request->get('last_name');
        $transport->email = $request->get('email');
        $transport->phone = $request->get('phone');
        $transport->job_title = $request->get('job_title');

        $transport->save();

        return redirect()->route('transports.show', $transport->id)->with('success', 'Transport updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transport = Transport::find($id);
        $transport->delete();

        return redirect()->route('transports.index')->with('success', 'Transport successfully deleted!');
    }
}

resources/views/transports/create.blade.php
@extends('layouts.app')

@section('title', 'New Transport')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <form action="{{ route('transports.store') }}" method="post">
        @csrf
        <div class="form-group"><label for="name">Company</label><input type="text" name="name" id="name" class="form-control"></div>
        <div class="form-row">
            <div class="form-group col-md"><label for="first_name">First Name</label><input type="text" name="first_name" id="first_name" class="form-control"></div>
            <div class="form-group col-md"><label for="last_name">Last Name</label><input type="text" name="last_name" id="last_name" class="form-control"></div>
            <div class="form-group col-md"><label for="job_title">Job Title</label><input type="text" name="job_title" id="job_title" class="form-control"></div>
        </div>
        <div class="form-row">
            <div class="form-group col-md"><label for="email">Email</label><input type="email" name="email" id="email" class="form-control"></div>
            <div class="form-group col-md"><label for="phone">Phone</label><input type="text" name="phone" id="phone" class="form-control"></div>
        </div>
        <div class="form-group"><button type="submit" class="btn btn-primary mr-3">Save</button><a href="{{ route('transports.index') }}" class="btn btn-danger">Cancel</a></div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/transports/edit.blade.php
@extends('layouts.app')

@section('title', 'Update Transport')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <form action="{{ route('transports.update', $transport->id) }}" method="post">
        @csrf
        @method('PATCH')
        <div class="form-group"><label for="name">Company</label><input type="text" name="name" id="name" class="form-control" value="{{ $transport->name }}"></div>
        <div class="form-row">
            <div class="form-group col-md"><label for="first_name">First Name</label><input type="text" name="first_name" id="first_name" class="form-control" value="{{ $transport->first_name }}"></div>
            <div class="form-group col-md"><label for="last_name">Last Name</label><input type="text" name="last_name" id="last_name" class="form-control" value="{{ $transport->last_name }}"></div>
            <div class="form-group col-md"><label for="job_title">Job Title</label><input type="text" name="job_title" id="job_title" class="form-control" value="{{ $transport->job_title }}"></div>
        </div>
        <div class="form-row">
            <div class="form-group col-md"><label for="email">Email</label><input type="email" name="email" id="email" class="form-control" value="{{ $transport->email }}"></div>
            <div class="form-group col-md"><label for="phone">Phone</label><input type="text" name="phone" id="phone" class="form-control" value="{{ $transport->phone }}"></div>
        </div>
        <div class="form-group"><button type="submit" class="btn btn-primary mr-3">Update</button><a href="{{ route('transports.index') }}" class="btn btn-danger">Cancel</a></div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/transports/index.blade.php
@extends('layouts.app')

@section('title', 'Transports')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <a href="{{ route('transports.create') }}" class="btn btn-primary mb-2">New Transport</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Company</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach ($transports as $transport)
                <tr>
                    <td><a href="{{ route('transports.show', $transport->id) }}">{{ $transport->name }}</a></td>
                    <td class="text-right">
                        <form action="{{ route('transports.destroy', $transport->id) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">X</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    </div>
</div>
@endsection

resources/views/transports/show.blade.php
@extends('layouts.app')

@section('title', $transport->name)

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
        <table class="table">
            <tr>
                <th>Contact Name:</th>
                <td>{{ $transport->first_name }} {{ $transport->last_name }}</td>
            </tr>
            <tr>
                <th>Job Title:</th>
                <td>{{ $transport->job_title }}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{ $transport->email }}</td>
            </tr>
            <tr>
                <th>Phone:</th>
                <td>{{ $transport->phone }}</td>
            </tr>
        </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <a href="{{ route('transports.edit', $transport->id) }}" class="btn btn-outline-secondary">Update</a>
            <form action="{{ route('transports.destroy', $transport->id) }}" method="post" style="display: inline;">
                @csrf
                @method('DELETE')
                <button class="btn btn-outline-danger" type="submit">Delete</button>
            </form>
        </div>
    </div>
</div>
@endsection